version: "3.8"
services:
  mysql_gabbler:
    image: mysql:8
    restart: always
    environment:
      - MYSQL_DATABASE=gabbler
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3307:3306
  pma_gabbler:
    image: phpmyadmin/phpmyadmin:5
    restart: always
    ports:
      - 8090:80
    links:
      - mysql_gabbler:mysql_gabbler
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      PMA_ARBITRARY: 1
      PMA_HOST: mysql_gabbler