info:
  app:
    name: gabbler-api
    description: A simple social network
    version: '@project.version@'
    build: '@buildNumber@'

server:
  port: 8081


spring:
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: yanis.houdier@gmail.com
    password: dkopandgxvhtgihg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


openapi:
  file:
    path: ./gabbler-desc/target/generated-sources/openapi-generator-json/openapi.json