server:
  port: 8081
spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://localhost/gabbler?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 738072251882-fi33qasvg36to97lajbkqo2m4f6fb9mv.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
  mustache:
    check-template-location: false
info:
  app:
    name: gabbler-api
    description: A simple social network
    version: '@project.version@'
    build: '@buildNumber@'
