info:
  app:
    name: gabbler-api
    description: A simple social network
    version: '@project.version@'
    build: '@buildNumber@'

server:
  port: 8081


spring:
  main:
    allow-circular-references: true
openapi:
  file:
    path: ./gabbler-desc/target/generated-sources/openapi-generator-json/openapi.json