server:
  port: 8081
spring:
  security:
    oauth2:
      client:
        registration:
          oauth2:
            client-id: gabbler
            client-secret: gabbler
            scope: openid, profile, roles
            authorization-grant-type: password
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: post
            provider: keycloak
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/gabbler
            token-uri: http://localhost:8080/realms/gabbler/protocol/openid-connect/token

info:
  app:
    name: gabbler-api
    description: A simple social network
    version: '@project.version@'
    build: '@buildNumber@'
keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: gabbler
  resource: gabbler
  ssl-required: external
  public-client: true