info:
  app:
    name: gabbler-api
    description: A simple social network
    version: '@project.version@'
    build: '@buildNumber@'

server:
  port: 8081

spring:
  application:
    name: gabbler-keycloak
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/gabbler
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

jwt:
  auth:
    converter:
      resource-id: gabbler-client
      principal-attribute: preferred_username

logging:
  level:
    org.springframework.security: DEBUG

openapi:
  file:
    path: ./gabbler-desc/target/generated-sources/openapi-generator-json/openapi.json