info:
  app:
    name: gabbler-api
    description: A simple social network
    version: '@project.version@'
    build: '@buildNumber@'

server:
  port: 8081
  
spring:
  security:
    oauth2:
      client:
        registration:
          oauth2:
            client-id: gabbler
            client-secret: gabbler
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/auth/realms/Gabbler
            token-uri: http://localhost:8080/auth/realms/Gabbler/protocol/openid-connect/token

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: Gabbler
  resource: gabbler
  ssl-required: external
  public-client: true