openapi: 3.0.3
info:
  title: Modèle de l'api Gabbler en mode rest
  description: Modèle de l'api Gabbler en mode rest
  version: 1.0.0
tags:
  - name: user
    description: Opérations sur les utilisateurs
paths: { }
components:
  schemas:

    User:
      type: object
      description: objet correspondant à un utilisateur
      properties:
        id:
          type: integer
          description: id de l'utilisateur
          example: "25"
        username:
          type: string
          description: pseudonyme de l'utilisateur
          example: "Sinsay"
        firstname:
          type: string
          description: prénom de l'utilisateur
          example: "Yanis"
        lastname:
          type: string
          description: nom de l'utilisateur
          example: "Houdier"
        birthday:
          type: string
          description: date d'anniversaire de l'utilisateur
          example: "2001-07-28"
        email:
          type: string
          description: email de l'utilisateur
          example: "yanis.houdier@gmail.com"
        biography:
          type: string
          description: biographie de l'utilisateur
          example: "yanis 21 ans célibataire suuuuu"

    Users:
      type: object
      description: objet correspondant à une liste d'utilisateurs
      properties:
        users:
          type: array
          description: liste d'utilisateurs
          items:
            $ref: "#/components/schemas/User"

    AccessError:
      type: object
      description: objet correspondant à une erreur d'accès
      properties:
        error:
          description: code de l'erreur
          type: string
          example: "BAD_REQUEST"
        message:
          description: message détaillant l'erreur
          type: string
          example: "La valeur du champ 'text' ne peut pas contenir 'test' !"
        path:
          description: indique le path ayant provoqué cette erreur
          type: string
          example: "/user/9ebd6eff-136f-429a-b946-0fb13a314d42/load"

    Gab:
      type: object
      description: objet correspondant à un gab
      properties:
        id:
          type: integer
          example: "56"
        content:
          type: string
          description: contenu du gab
          example: "Ratio macron, vive la république!"
        post_date:
          type: string
          description: date de publication du gab
          example: "2023-01-25"