openapi: 3.0.3
info:
  title: Modèle de l'api Gabbler en mode rest
  description: Modèle de l'api Gabbler en mode rest
  version: 1.0.0
tags:
  - name: user
    description: Opérations sur les utilisateurs
  - name: gab
    description: Opérations sur les gabs
  - name: doc
    description: Opérations sur le json doc
  - name: auth
    description: Opérations d'authentification
paths: { }
components:
  schemas:
    JsonDoc:
      type: string
      description: objet correspondant à la documentation json
      format: json

    User:
      type: object
      description: objet correspondant à un utilisateur
      properties:
        uuid:
          type: string
          description: uuid de l'utilisateur
          example: "9ebd6eff-136f-429a-b946-0fb13a314d42"
        username:
          type: string
          description: pseudonyme de l'utilisateur
          example: "Sinsay"
        firstname:
          type: string
          description: prénom de l'utilisateur
          example: "Yanis"
        lastname:
          type: string
          description: nom de l'utilisateur
          example: "Houdier"
        birthday:
          type: string
          description: date d'anniversaire de l'utilisateur
          example: "2001-07-28"
        email:
          type: string
          description: email de l'utilisateur
          example: "yanis.houdier@gmail.com"
        biography:
          type: string
          description: biographie de l'utilisateur
          example: "yanis 21 ans célibataire suuuuu"

    Users:
      type: object
      description: objet correspondant à une liste d'utilisateurs
      properties:
        users:
          type: array
          description: liste d'utilisateurs
          items:
            $ref: "#/components/schemas/User"

    Gab:
      type: object
      description: objet correspondant à un gab
      properties:
        id:
          type: integer
          example: "56"
        content:
          type: string
          description: contenu du gab
          example: "Ratio macron, vive la république!"
        post_date:
          type: string
          description: date de publication du gab
          example: "2023-01-25 18:17:35"
        nbLikes:
          type: integer
          description: nombre de likes du gab
          example: "5"
        nbDislikes:
          type: integer
          description: nombre de dislikes du gab
          example: "2"
        nbComments:
          type: integer
          description: nombre de commentaires du gab
          example: "3"
        user:
          $ref: "#/components/schemas/User"

    Gabs:
      type: object
      description: objet correspondant à une liste de gabs
      properties:
        gabs:
          type: array
          description: liste de gabs
          items:
            $ref: "#/components/schemas/Gab"

    GabCreation:
      type: object
      description: objet correspondant à un gab pour sa création
      properties:
        content:
          type: string
          description: contenu du gab
          example: "Ratio macron, vive la république!"
        post_date:
          type: string
          description: date de publication du gab
          example: "2023-01-25 18:17:35"
        parent_gab_id:
          type: integer
          description: id du gab parent
          example: "56"
        user_uuid:
          type: string
          description: uuid de l'utilisateur
          example: "9ebd6eff-136f-429a-b946-0fb13a314d42"
    UserAndToken:
      type: object
      description: objet correspondant à un utilisateur avec son jeton d'authentification
      properties:
        token:
          type: string
          description: jeton d'authentification de l'utilisateur
        user:
          $ref: "#/components/schemas/User"

    UserAuth:
      type: object
      description: objet correspondant à un utilisateur avec son mot de passe
      properties:
        email:
          type: string
          description: email de l'utilisateur
          example: "yanis.houdier@gmail.com"
        password:
          type: string
          description: mot de passe de l'utilisateur
          example: "123456"

    UserRegister:
      type: object
      description: objet correspondant aux informations d'un utilisateur pour l'inscription
      properties:
        email:
          type: string
          description: email de l'utilisateur
          example: "nom.prenom@gmal.com"
        password:
          type: string
          description: mot de passe de l'utilisateur
          example: "123456"
        username:
          type: string
          description: pseudonyme de l'utilisateur
          example: "Sinsay"
        firstname:
          type: string
          description: prénom de l'utilisateur
          example: "Yanis"
        lastname:
          type: string
          description: nom de l'utilisateur
          example: "Houdier"
        birthday:
          type: string
          description: date d'anniversaire de l'utilisateur
          example: "2001-07-28"


    AccessError:
      type: object
      description: objet correspondant à une erreur d'accès
      properties:
        error:
          description: code de l'erreur
          type: string
          example: "BAD_REQUEST"
        message:
          description: message détaillant l'erreur
          type: string
          example: "La valeur du champ 'text' ne peut pas contenir 'test' !"
        path:
          description: indique le path ayant provoqué cette erreur
          type: string
          example: "/user/9ebd6eff-136f-429a-b946-0fb13a314d42/load"
